Исключение в работе ЦП: Физическое повреждение одного из ядер
	at task5.Main.main(Main.java:22)
